// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class Arms {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Arms {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsArms(bb:flatbuffers.ByteBuffer, obj?:Arms):Arms {
  return (obj || new Arms()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsArms(bb:flatbuffers.ByteBuffer, obj?:Arms):Arms {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Arms()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

count():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

static startArms(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addCount(builder:flatbuffers.Builder, count:number) {
  builder.addFieldInt8(0, count, 0);
}

static endArms(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createArms(builder:flatbuffers.Builder, count:number):flatbuffers.Offset {
  Arms.startArms(builder);
  Arms.addCount(builder, count);
  return Arms.endArms(builder);
}
}
