// automatically generated by the FlatBuffers compiler, do not modify

export { Equipment } from './equipment';
export { Monster } from './monster';
export { Shield } from './shield';
export { Sword } from './sword';
