// automatically generated by the FlatBuffers compiler, do not modify

export { Equipment } from './equipment';
export { Monster, MonsterT } from './monster';
export { Shield, ShieldT } from './shield';
export { Sword, SwordT } from './sword';
